import { ChildrenProps } from "@/types/props";

export const metadata = {
  title: "Spotify Private | Song Detail",
  description: "Generated by create next app",
};
function SongDetailLayout({ children }: ChildrenProps) {
  return <div className="container flex items-center justify-center">{children}</div>;
}
export default SongDetailLayout;
