import { Metadata } from "next";

import { Separator } from "@/components/ui/separator";
import { ChildrenProps } from "@/types/props";

export async function generateMetadata({ params }: { params: Promise<{ category: string }> }): Promise<Metadata> {
  const { category } = await params;
  const decodedCategory = decodeURIComponent(category);

  return {
    title: `Spotify Private | ${decodedCategory}`,
    description: "Generated by create next app",
  };
}

export default async function SearchSongsWithCategoryLayout(
  { params, children }: { params: Promise<{ category: string }>, children: React.ReactNode }
) {
  const { category } = await params; // ✅ ต้อง await ก่อน
  const decodedCategory = decodeURIComponent(category);

  return (
    <div className="min-h-screen">
      {/* Header เต็มจอ */}
      <header className="w-full flex flex-col justify-end h-40 py-5 bg-gradient-to-br from-blue-500 to-gray-800">
        <h1 className="text-4xl font-bold px-5 text-white">{ decodedCategory }</h1>
      </header>

      <Separator />

      {/* เนื้อหาหลักใช้ container */}
      <main className="container my-5">
        {children}
      </main>
    </div>
  );
}
