import { Metadata } from "next";

import { ChildrenProps } from "@/types/props";

export async function generateMetadata({ params }: { params: Promise<{ category: string }> }): Promise<Metadata> {
  const { category } = await params;
  const decodedCategory = decodeURIComponent(category);

  return {
    title: `Spotify Private | ${decodedCategory}`,
    description: "Generated by create next app",
  };
}

function SearchSongsWithCategoryLayout({ children }: ChildrenProps) {
  return <div className="container flex min-h-screen flex-col items-center sm:mx-auto px-4 md:px-0"> {children} </div>;
}
export default SearchSongsWithCategoryLayout;
