import { ChildrenProps } from "@/types/props";

// layout.tsx
export const metadata = {
  title: 'Forgot Password',
  description: 'Generated by create next app',
};

export default function Layout({ children }: ChildrenProps) {
  return (
    <div className="flex items-center justify-center min-h-screen ">
      {children}
    </div>
  );
}
