import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai, Poppins } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";

import AppLayout from "@/components/layout/wrap/AppLayout";
import { ClientLayout } from "@/components/layout/wrap";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify Clone : Private",
  description: "Generated by create next app",
  keywords:["Spotify","Clone","Music","Private","Next.js","Tailwind","React","Shadcn UI"],
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = typeof window !== "undefined" ? window.location.pathname : "";
  const isAuthPage = ["/forgot-password","/reset-password" ].includes(pathname);
 

  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${notoSansThai.className} antialiased`}
      >
       {isAuthPage ? (
          children // แสดงเฉพาะ children (ไม่ต้องใช้ ClientLayout / AppLayout)
        ) : (
          <ClientLayout>
            <AppLayout>{children}</AppLayout>
          </ClientLayout>
        )}
      </body>
    </html>
  );
}
