import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai, Poppins } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/layout/ClientLayout";
import Navbar from "@/components/layout/Navbar";
import ReduxProvider from "@/components/layout/ReduxProvider";
import { Toaster } from "react-hot-toast";
import SideBar from "@/components/layout/SideBar";
import AuthSessionProvider from "@/components/layout/AuthSession";
import AppLayout from "@/components/layout/AppLayout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${notoSansThai.className} antialiased`}
      >
        <ClientLayout>
           <AppLayout>{children}</AppLayout>
        </ClientLayout>
      </body>
    </html>
  );
}
